language: cpp

install:
- touch configure aclocal.m4 Makefile.in
- wget http://ftpmirror.gnu.org/bison/bison-3.5.tar.gz
- tar -xf bison-3.5.tar.gz
- cd bison-3.5; ./configure && make && sudo make install; cd ..
- sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"

script: ./configure && make && make check

compiler:
- gcc
- clang

addons:
  apt:
    packages:
    - m4
    - flex
    - libboost-filesystem-dev