name: C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v1
    - name: Get Bison
      run: wget http://ftpmirror.gnu.org/bison/bison-3.5.tar.gz; tar -xzf bison-3.5.tar.gz; cd bison-3.5; ./configure && make && sudo make install; cd ..
    - name: Get LLVM
      run: bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
    - name: Get other libraries
      run: sudo apt-get install libboost-filesystem-dev m4 flex
    - name: Configure environment
      run: touch configure aclocal.m4 Makefile.in; ./configure
    - name: Compile
      run: make
    - name: Test
      run: make check
